@jwt= eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxMDE1MTR9.yDSzV5NQWPh3coGLVhTv8aZLfp0ZxX3RhJQKcmOk_VQ

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos Index
GET http://localhost:3000/photos.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Photos Show
GET http://localhost:3000/photos/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "image_url": "Test image url",
  "date": "10/10/2020",
  "description": 480,
  "user_id": 1
}

### Photos update
PATCH http://localhost:3000/photos/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeFM9JOXeqml4nCZzr4522iWeM-EAnkgkVjg&usqp=CAU",
  "date": "10/10/2020",
  "description": "test description!!!!!!!!!!!!!!!!!!",
  "user_id": 2
  
}

### Photos Destroy
DELETE  http://localhost:3000/photos/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json