### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos Index
GET http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxNjY3MDN9.sOUWMTnsk1RhZwBjaUV0IanRHw6JXLL5bLC-_L3vkho

### Photos Show
GET http://localhost:3000/photos/2.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxNjY3MDN9.sOUWMTnsk1RhZwBjaUV0IanRHw6JXLL5bLC-_L3vkho

### Photos create
POST http://localhost:3000/photos.json
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxNjY3MDN9.sOUWMTnsk1RhZwBjaUV0IanRHw6JXLL5bLC-_L3vkho

{
  "image_url": "2nd test image url",
  "date": "10/10/2020",
  "description": "Test descrption"
}

### Photos update
PATCH http://localhost:3000/photos/2\4.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxNjY3MDN9.sOUWMTnsk1RhZwBjaUV0IanRHw6JXLL5bLC-_L3vkho

{
 "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeFM9JOXeqml4nCZzr4522iWeM-EAnkgkVjg&usqp=CAU",
  "date": "10/10/2020",
  "description": "test description"
}

### Photos Destroy
DELETE  http://localhost:3000/photos/4.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcxNjY3MDN9.sOUWMTnsk1RhZwBjaUV0IanRHw6JXLL5bLC-_L3vkho
Content-Type: application/json